# fly.toml app configuration file generated for runaly on 2024-03-04T12:52:07+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'runaly'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
